services:
  oapi-codegen:
    build:
      dockerfile: docker/go-codegen.Dockerfile
    volumes:
      - ./:/src/go/app
    working_dir: /src/go/app
    command: >
      sh -c '
      oapi-codegen -config ./openapi/oapi-codegen/server.config.yml ./openapi/schema.yml &&
      oapi-codegen -config ./openapi/oapi-codegen/model.config.yml ./openapi/schema.yml &&
      oapi-codegen -config ./openapi/oapi-codegen/client.config.yml ./openapi/schema.yml
      '

  gqlgen:
    build:
      dockerfile: docker/go-codegen.Dockerfile
    volumes:
      - ./:/src/go/app
    working_dir: /src/go/app/go/gqlgen
    command: >
      sh -c '
      gqlgen generate
      '

  grpc:
    build:
      dockerfile: docker/go-codegen.Dockerfile
    volumes:
      - ./:/src/go/app
    working_dir: /src/go/app/go/grpc
    command: >
      sh -c '
        protoc --go_out=./pkg/grpc --go_opt=paths=source_relative \
        --go-grpc_out=./pkg/grpc --go-grpc_opt=paths=source_relative \
        hello.proto
      '
